import "../styles/modern-normalize.css"
import "../styles/styles.css"
import "../styles/components/header.css"
import "../styles/components/info.css"
import "../styles/components/prop.css"
import "../styles/utils.css"
import weatherData from "./weather.js"
import Dom from "./dom.js"